apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-api
  namespace: cleo
  labels:
    app: atlas-api
    tier: backend
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-api
  template:
    metadata:
      labels:
        app: atlas-api
        tier: backend
    spec:
      containers:
      - name: atlas-api
        image: 235494787311.dkr.ecr.us-east-2.amazonaws.com/atlas-api:latest  
        ports:
        - containerPort: 8008
        env:
        - name: URL_PREFIX
          value: "atlas-kuzudb"
        - name: AWS_REGION
          value: "us-east-2"
        command: ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8008}"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-api-service
  namespace: cleo
  labels:
    app: atlas-api
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8008
    targetPort: 8008
    protocol: TCP
  selector:
    app: atlas-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: atlas-api-hpa
  namespace: cleo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atlas-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
